#!/bin/sh

# build spring app image
sudo docker build -t game-center .

# create network
sudo docker network create game-center-network

# start db container
sudo docker run -d -p 5432:5432 --rm --name pgdb --net game-center-network \
                -v /home/aguerre/Game-Center-Database:/var/lib/postgresql/data \
                -e POSTGRES_PASSWORD=postgres postgres

# start spring container
sudo docker run -it -p 8080:8080 --rm --name game-center --net game-center-network \
    -e SPRING_PROFILES_ACTIVE=docker \
    -e SPRING_DATASOURCE_PASSWORD=postgres \
    -e SPRING_DATASOURCE_USERNAME=postgres \
    game-center


